;;; rust-auto-use-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from rust-auto-use.el

(autoload 'rust-auto-use "rust-auto-use" "\
Attempts to insert a required `use` statement for the symbol at point." t nil)
(register-definition-prefixes "rust-auto-use" '("rust-auto-use-"))

;;; End of scraped data

(provide 'rust-auto-use-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8-emacs-unix
;; End:

;;; rust-auto-use-autoloads.el ends here
