;;; flycheck-plantuml-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from flycheck-plantuml.el

(autoload 'flycheck-plantuml-setup "flycheck-plantuml" "\
Setup flycheck-plantuml.

Add `plantuml' to `flycheck-checkers'." t nil)

;;; End of scraped data

(provide 'flycheck-plantuml-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8-emacs-unix
;; End:

;;; flycheck-plantuml-autoloads.el ends here
