;;; feebleline-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from feebleline.el

(defvar feebleline-mode nil "\
Non-nil if Feebleline mode is enabled.
See the `feebleline-mode' command
for a description of this minor mode.
Setting this variable directly does not take effect;
either customize it (see the info node `Easy Customization')
or call the function `feebleline-mode'.")
(custom-autoload 'feebleline-mode "feebleline" nil)
(autoload 'feebleline-mode "feebleline" "\
Replace modeline with a slimmer proxy.

This is a global minor mode.  If called interactively, toggle the
`Feebleline mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='feebleline-mode)'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t nil)
(register-definition-prefixes "feebleline" '("feebleline-"))

;;; End of scraped data

(provide 'feebleline-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8-emacs-unix
;; End:

;;; feebleline-autoloads.el ends here
