;;; langtool-ignore-fonts-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from langtool-ignore-fonts.el

(autoload 'langtool-ignore-fonts-minor-mode "langtool-ignore-fonts" "\
Automically remove `langtool' overlays with font matching `langtool-ignore-fonts'

This is a minor mode.  If called interactively, toggle the
`Langtool-Ignore-Fonts minor mode' mode.  If the prefix argument
is positive, enable the mode, and if it is zero or negative,
disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `langtool-ignore-fonts-minor-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t nil)
(register-definition-prefixes "langtool-ignore-fonts" '("langtool-ignore-fonts"))

;;; End of scraped data

(provide 'langtool-ignore-fonts-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8-emacs-unix
;; End:

;;; langtool-ignore-fonts-autoloads.el ends here
