;;; git-messenger-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from git-messenger.el

(autoload 'git-messenger:popup-message "git-messenger" nil t nil)
(register-definition-prefixes "git-messenger" '("git-messenger"))

;;; End of scraped data

(provide 'git-messenger-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8-emacs-unix
;; End:

;;; git-messenger-autoloads.el ends here
